
server:
  port: 8082
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Myweb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: j@9damba
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      continue-on-error: false